Fix for Github workflow
For some reason when running the checks on Github the code fails with
the following error:

```
 chalk/backend/cairo.py:42: error: Unused "type: ignore" comment
            return cairo.Matrix(a, d, b, e, c, f)  # type: ignore
```

Locally checks (`make type`) work fine, using the same version of mypy
(0.991). To fix this incompatibility I will resort for now to ignore the
errors caused by unused ignores.